io:
  use_camera: false        # false: file input, true: camera input
  camera_port: 0           # camera device index
  input_file_path: "./data/test.mp4"  # input video file path
  scale: 2                # image downscale factor
  save_results: true       # save CSV and video results

hog:
  bin_count: 180           # histogram bin count
  threshold_value: 0.25    # magnitude threshold for binary filtering
  blur_kernel_size: 11      # Gaussian blur kernel size
  blur_sigma: 3.0          # Gaussian blur sigma
  erode_kernel_size: 3      # erosion kernel size for magnitude filtering

vv_estimator:
  min_angle: 30            # minimum angle of interest (degrees)
  max_angle: 150           # maximum angle of interest (degrees)
  smoothing_factor: 0.7    # smoothing weight (0.0-1.0)